#!/usr/bin/env bash
path=$1
ip=$2
user=$3
key=$4
if [ $# -lt 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi
scp StrictHostKeyChecking=no -i "$key" "$path" "$user"@"$ip":~/ 
