#!/usr/bin/env bash
#setting up a new ubuntu machine

sudo apt-get update

sudo apt-get install -y nginx

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

sudo bash -c 'cat << EOF > /var/www/html/index.html
Hello World!
EOF'

sudo service nginx restart
